
defaults:
  - dataset: 
  - logging: 
  - optimizer: 
  - scheduler: 
  - model: 
  - callbacks: 
  - data:
  - dataset:
  - datamodule:
  - augmentation: 

general:
  save_dir:
  project_name: 
  device: 

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
  sweep:
    dir: outputs/
    subdir: ${now:%Y_%m_%d_%H_%M_%S}